openapi: 3.0.0
info:
  title: 'Hello API Platform'
  description: ''
  version: 1.0.0
servers:
  -
    url: /
    description: ''
paths:
  /greetings:
    get:
      operationId: api_greetings_get_collection
      tags:
        - Greeting
      responses:
        200:
          description: 'Greeting collection'
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  'hydra:member': { type: array, items: { $ref: '#/components/schemas/Greeting.jsonld' } }
                  'hydra:totalItems': { type: integer, minimum: 0 }
                  'hydra:view': { type: object, properties: { '@id': { type: string, format: iri-reference }, '@type': { type: string }, 'hydra:first': { type: string, format: iri-reference }, 'hydra:last': { type: string, format: iri-reference }, 'hydra:previous': { type: string, format: iri-reference }, 'hydra:next': { type: string, format: iri-reference } }, example: { '@id': string, type: string, 'hydra:first': string, 'hydra:last': string, 'hydra:previous': string, 'hydra:next': string } }
                  'hydra:search': { type: object, properties: { '@type': { type: string }, 'hydra:template': { type: string }, 'hydra:variableRepresentation': { type: string }, 'hydra:mapping': { type: array, items: { type: object, properties: { '@type': { type: string }, variable: { type: string }, property: { type: string, nullable: true }, required: { type: boolean } } } } } }
                required:
                  - 'hydra:member'
            application/hal+json:
              schema:
                type: object
                properties:
                  _embedded: { type: array, items: { $ref: '#/components/schemas/Greeting.jsonhal' } }
                  totalItems: { type: integer, minimum: 0 }
                  itemsPerPage: { type: integer, minimum: 0 }
                  _links: { type: object, properties: { self: { type: object, properties: { href: { type: string, format: iri-reference } } }, first: { type: object, properties: { href: { type: string, format: iri-reference } } }, last: { type: object, properties: { href: { type: string, format: iri-reference } } }, next: { type: object, properties: { href: { type: string, format: iri-reference } } }, previous: { type: object, properties: { href: { type: string, format: iri-reference } } } } }
                required:
                  - _links
                  - _embedded
            application/vnd.api+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Greeting'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Greeting'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Greeting'
            text/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Greeting'
            application/x-yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Greeting'
            text/csv:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Greeting'
            text/html:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Greeting'
      summary: 'Retrieves the collection of Greeting resources.'
      description: 'Retrieves the collection of Greeting resources.'
      parameters:
        -
          name: page
          in: query
          description: 'The collection page number'
          required: false
          deprecated: false
          allowEmptyValue: true
          schema:
            type: integer
            default: 1
          style: form
          explode: false
          allowReserved: false
      deprecated: false
    post:
      operationId: api_greetings_post
      tags:
        - Greeting
      responses:
        201:
          description: 'Greeting resource created'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Greeting.jsonld'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Greeting.jsonhal'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Greeting'
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'
            application/xml:
              schema:
                $ref: '#/components/schemas/Greeting'
            text/xml:
              schema:
                $ref: '#/components/schemas/Greeting'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Greeting'
            text/csv:
              schema:
                $ref: '#/components/schemas/Greeting'
            text/html:
              schema:
                $ref: '#/components/schemas/Greeting'
          links: {  }
        400:
          description: 'Invalid input'
        422:
          description: 'Unprocessable entity'
      summary: 'Creates a Greeting resource.'
      description: 'Creates a Greeting resource.'
      parameters: []
      requestBody:
        description: 'The new Greeting resource'
        content:
          application/ld+json:
            schema:
              $ref: '#/components/schemas/Greeting.jsonld'
          application/hal+json:
            schema:
              $ref: '#/components/schemas/Greeting.jsonhal'
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/Greeting'
          application/json:
            schema:
              $ref: '#/components/schemas/Greeting'
          application/xml:
            schema:
              $ref: '#/components/schemas/Greeting'
          text/xml:
            schema:
              $ref: '#/components/schemas/Greeting'
          application/x-yaml:
            schema:
              $ref: '#/components/schemas/Greeting'
          text/csv:
            schema:
              $ref: '#/components/schemas/Greeting'
          text/html:
            schema:
              $ref: '#/components/schemas/Greeting'
        required: true
      deprecated: false
    parameters: []
  '/greetings/{id}':
    get:
      operationId: api_greetings_id_get
      tags:
        - Greeting
      responses:
        200:
          description: 'Greeting resource'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Greeting.jsonld'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Greeting.jsonhal'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Greeting'
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'
            application/xml:
              schema:
                $ref: '#/components/schemas/Greeting'
            text/xml:
              schema:
                $ref: '#/components/schemas/Greeting'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Greeting'
            text/csv:
              schema:
                $ref: '#/components/schemas/Greeting'
            text/html:
              schema:
                $ref: '#/components/schemas/Greeting'
        404:
          description: 'Resource not found'
      summary: 'Retrieves a Greeting resource.'
      description: 'Retrieves a Greeting resource.'
      parameters:
        -
          name: id
          in: path
          description: 'Greeting identifier'
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    put:
      operationId: api_greetings_id_put
      tags:
        - Greeting
      responses:
        200:
          description: 'Greeting resource updated'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Greeting.jsonld'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Greeting.jsonhal'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Greeting'
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'
            application/xml:
              schema:
                $ref: '#/components/schemas/Greeting'
            text/xml:
              schema:
                $ref: '#/components/schemas/Greeting'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Greeting'
            text/csv:
              schema:
                $ref: '#/components/schemas/Greeting'
            text/html:
              schema:
                $ref: '#/components/schemas/Greeting'
          links: {  }
        400:
          description: 'Invalid input'
        422:
          description: 'Unprocessable entity'
        404:
          description: 'Resource not found'
      summary: 'Replaces the Greeting resource.'
      description: 'Replaces the Greeting resource.'
      parameters:
        -
          name: id
          in: path
          description: 'Greeting identifier'
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      requestBody:
        description: 'The updated Greeting resource'
        content:
          application/ld+json:
            schema:
              $ref: '#/components/schemas/Greeting.jsonld'
          application/hal+json:
            schema:
              $ref: '#/components/schemas/Greeting.jsonhal'
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/Greeting'
          application/json:
            schema:
              $ref: '#/components/schemas/Greeting'
          application/xml:
            schema:
              $ref: '#/components/schemas/Greeting'
          text/xml:
            schema:
              $ref: '#/components/schemas/Greeting'
          application/x-yaml:
            schema:
              $ref: '#/components/schemas/Greeting'
          text/csv:
            schema:
              $ref: '#/components/schemas/Greeting'
          text/html:
            schema:
              $ref: '#/components/schemas/Greeting'
        required: true
      deprecated: false
    delete:
      operationId: api_greetings_id_delete
      tags:
        - Greeting
      responses:
        204:
          description: 'Greeting resource deleted'
        404:
          description: 'Resource not found'
      summary: 'Removes the Greeting resource.'
      description: 'Removes the Greeting resource.'
      parameters:
        -
          name: id
          in: path
          description: 'Greeting identifier'
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    patch:
      operationId: api_greetings_id_patch
      tags:
        - Greeting
      responses:
        200:
          description: 'Greeting resource updated'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Greeting.jsonld'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Greeting.jsonhal'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Greeting'
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'
            application/xml:
              schema:
                $ref: '#/components/schemas/Greeting'
            text/xml:
              schema:
                $ref: '#/components/schemas/Greeting'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Greeting'
            text/csv:
              schema:
                $ref: '#/components/schemas/Greeting'
            text/html:
              schema:
                $ref: '#/components/schemas/Greeting'
          links: {  }
        400:
          description: 'Invalid input'
        422:
          description: 'Unprocessable entity'
        404:
          description: 'Resource not found'
      summary: 'Updates the Greeting resource.'
      description: 'Updates the Greeting resource.'
      parameters:
        -
          name: id
          in: path
          description: 'Greeting identifier'
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      requestBody:
        description: 'The updated Greeting resource'
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/Greeting'
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/Greeting'
        required: true
      deprecated: false
    parameters: []
components:
  schemas:
    Greeting:
      type: object
      description: 'This is a dummy entity. Remove it!'
      deprecated: false
      properties:
        id:
          readOnly: true
          description: 'The entity ID'
          type: integer
        name:
          description: 'A nice person'
          type: string
      required:
        - name
    Greeting.jsonhal:
      type: object
      description: 'This is a dummy entity. Remove it!'
      deprecated: false
      properties:
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  format: iri-reference
        id:
          readOnly: true
          description: 'The entity ID'
          type: integer
        name:
          description: 'A nice person'
          type: string
      required:
        - name
    Greeting.jsonld:
      type: object
      description: 'This is a dummy entity. Remove it!'
      deprecated: false
      properties:
        '@context':
          readOnly: true
          oneOf:
            -
              type: string
            -
              type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum: ['http://www.w3.org/ns/hydra/core#']
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        id:
          readOnly: true
          description: 'The entity ID'
          type: integer
        name:
          description: 'A nice person'
          type: string
      required:
        - name
  responses: {  }
  parameters: {  }
  examples: {  }
  requestBodies: {  }
  headers: {  }
  securitySchemes: {  }
security: []
tags: []

